# Generated by Django 3.1.5 on 2021-01-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acao_governo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acaogoverno',
            table='acao_governo',
        ),
    ]
