# Generated by Django 3.1.5 on 2021-01-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natureza_despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='naturezadespesas',
            table='natureza_despesas',
        ),
    ]
