# Generated by Django 3.1.5 on 2021-01-31 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pi', '0002_auto_20210131_1941'),
        ('funcionarios', '0003_auto_20210131_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='pi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pi.pi'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
