# Generated by Django 3.1.5 on 2021-01-31 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0002_auto_20210131_1941'),
        ('funcionarios', '0005_auto_20210131_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pi.pi'),
        ),
    ]
