# Generated by Django 3.1.5 on 2021-02-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celulas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EMPENHADO', 'Empenhado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('PENDENTE', 'Pendente')], max_length=15)),
                ('celula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='celulas.celula')),
            ],
            options={
                'db_table': 'planejamentos',
            },
        ),
    ]
