# Generated by Django 3.1.5 on 2021-02-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pi', '0002_auto_20210131_1941'),
        ('fonte_recursos', '0002_auto_20210131_1941'),
        ('ug_responsavel', '0002_auto_20210131_1941'),
        ('acao_governo', '0002_auto_20210131_1941'),
        ('orcamentos', '0002_auto_20210131_1941'),
        ('ptres', '0002_auto_20210131_1941'),
        ('natureza_despesas', '0002_auto_20210131_1941'),
        ('ug_executora', '0002_auto_20210131_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dotacao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credito', models.DecimalField(decimal_places=2, max_digits=15)),
                ('despesasEmp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('despesasPagas', models.DecimalField(decimal_places=2, max_digits=15)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acao_governo.acaogoverno')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fonte_recursos.fonterecurso')),
                ('natureza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='natureza_despesas.naturezadespesas')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pi.pi')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orcamentos.orcamento')),
                ('ptres', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ptres.ptres')),
                ('ugex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ug_executora.ugexecutora')),
                ('ugresp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ug_responsavel.ugresponsavel')),
            ],
            options={
                'db_table': 'celulas',
            },
        ),
        migrations.AddConstraint(
            model_name='celula',
            constraint=models.UniqueConstraint(fields=('acao', 'plano', 'ptres', 'ugresp', 'ugex', 'pi', 'fonte', 'natureza'), name='unique_celula'),
        ),
    ]
