# Generated by Django 3.1.5 on 2021-02-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celulas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='celula',
            name='unique_celula',
        ),
        migrations.AddConstraint(
            model_name='celula',
            constraint=models.UniqueConstraint(fields=('acao', 'plano', 'ptres', 'ugresp', 'ugex', 'pi', 'fonte', 'natureza'), name='unique_celula'),
        ),
    ]
