# Generated by Django 3.1.5 on 2021-02-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celulas', '0002_auto_20210201_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='celula',
            name='descricao',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='celula',
            name='observacao',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
